image: mcr.microsoft.com/playwright:v1.61.0-noble

stages:
  - test

variables:
  PLAYWRIGHT_BROWSERS_PATH: /ms-playwright

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update
  - apt-get install -y default-jre wget unzip
  - wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
  - unzip -q allure-2.29.0.zip
  - mv allure-2.29.0 /opt/allure
  - ln -sf /opt/allure/bin/allure /usr/local/bin/allure
  - npm ci
  - npx playwright install --with-deps

playwright-api-test:
  stage: test

  script:
    - echo "Running Playwright API Tests..."
    - npx playwright test --project=api-tests-javascript

    - echo "Generating Allure Report..."
    - allure generate allure-results --clean -o allure-report

  artifacts:
    when: always
    expire_in: 7 days
    
    paths:
      - playwright-report/*
      - allure-results/*
      - allure-report/*
      - results.xml
      - results.json






